services:
  backend:
    image: olivertuesta/sotocks-info-backend:latest
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: olivertuesta/sotocks-info-frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge